name: 'Godot Engine 4.x Web Export (fixed)'
description: 'Enhanced: Ensures Web export templates are placed so Godot can find them'
author: 'acaValkyrie (modified)'

inputs:
  working-directory:
    description: 'The working directory (project root)'
    required: false
    default: '.'
  godot-version:
    description: 'Godot Engine version (4.x)'
    required: true
  godot-channel:
    description: 'Godot release channel (stable, beta, rc1...)'
    required: false
    default: 'stable'
  import-timeout-seconds:
    description: 'Timeout seconds for asset import'
    required: false
    default: '300'
  template-name:
    description: 'Name of export preset (Web)'
    required: false
    default: 'Web'

runs:
  using: "composite"
  steps:
    - name: Confirm Linux environment
      if: runner.os != 'Linux'
      shell: bash
      run: exit 1

    - name: Cache Godot binaries & templates
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}-${{ inputs.godot-channel }}

    - name: Download Godot & export templates if cache miss
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        VERSION=${{ inputs.godot-version }}
        CHANNEL=${{ inputs.godot-channel }}

        wget -q https://github.com/godotengine/godot-builds/releases/download/${VERSION}-${CHANNEL}/Godot_v${VERSION}-${CHANNEL}_linux.x86_64.zip
        wget -q https://github.com/godotengine/godot-builds/releases/download/${VERSION}-${CHANNEL}/Godot_v${VERSION}-${CHANNEL}_export_templates.tpz

        unzip -q Godot_v${VERSION}-${CHANNEL}_linux.x86_64.zip
        unzip -q Godot_v${VERSION}-${CHANNEL}_export_templates.tpz -d tmp_templates

        mkdir -p ~/.local/share/godot/export_templates/${VERSION}.${CHANNEL}
        cp tmp_templates/templates/web*.zip ~/.local/share/godot/export_templates/${VERSION}.${CHANNEL}/

        mv Godot_v${VERSION}-${CHANNEL}_linux.x86_64 /usr/local/bin/godot

    - name: Show template directory (for debugging)
      shell: bash
      run: |
        VERSION=${{ inputs.godot-version }}
        CHANNEL=${{ inputs.godot-channel }}
        ls -l ~/.local/share/godot/export_templates/${VERSION}.${CHANNEL}/

    - name: Import assets by launching headless editor
      shell: bash
      run: |
        timeout ${{ inputs.import-timeout-seconds }} godot --headless --path "${{ inputs.working-directory }}" -e || true

    - name: Export HTML5 to web/index.html
      shell: bash
      run: |
        mkdir -p web
        godot --headless --path "${{ inputs.working-directory }}" --export-release "${{ inputs.template-name }}" web/index.html

    - name: Display output directory
      shell: bash
      run: ls -R web

